import React, { useState } from 'react';
import { FileSpreadsheet, Download, Calendar, ArrowUpRight, CheckCircle2, Shield, FileText } from 'lucide-react';
import { AdminLayout } from '../../components/layout/AdminLayout';
import { AdminButton } from '../../components/ui/AdminButton';

export const ReportsPage: React.FC = () => {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const reportsList = [
    {
      id: 'REP-01',
      title: 'Q3 2026 Sales Ledger & Revenue Statement',
      category: 'Sales & Revenue',
      size: '2.4 MB',
      format: 'CSV / Excel',
      period: 'Jul 01 - Sep 30, 2026',
      generatedBy: 'Automated Store Accounting System',
    },
    {
      id: 'REP-02',
      title: 'Central Warehouse Inventory & Stock Audit',
      category: 'Inventory',
      size: '4.8 MB',
      format: 'CSV / XLSX',
      period: 'Monthly Audit (August 2026)',
      generatedBy: 'Warehouse Inventory Manager',
    },
    {
      id: 'REP-03',
      title: 'Customer Orders, Retention & VIP Client Report',
      category: 'Customers',
      size: '1.8 MB',
      format: 'CSV / PDF',
      period: 'Last 12 Months (2025-2026)',
      generatedBy: 'Customer Success Team',
    },
    {
      id: 'REP-04',
      title: 'GST, Sales Tax & Fiscal Invoicing Compliance',
      category: 'Tax & Compliance',
      size: '3.6 MB',
      format: 'CSV / PDF',
      period: 'Financial Year 2025-2026',
      generatedBy: 'Tax & Compliance Module',
    },
  ];

  const handleDownload = (rep: (typeof reportsList)[0]) => {
    setDownloadingId(rep.id);
    
    // Generate real CSV download
    const csvContent = `Report Title,${rep.title}\nCategory,${rep.category}\nPeriod,${rep.period}\nGenerated By,${rep.generatedBy}\nExport Date,${new Date().toLocaleDateString()}\nStatus,Certified & Verified\n`;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `${rep.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setTimeout(() => {
      setDownloadingId(null);
    }, 800);
  };

  return (
    <AdminLayout>
      <div className="p-4 sm:p-space-xl max-w-[1440px] mx-auto w-full space-y-space-lg">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <h1 className="font-display text-display text-primary tracking-tight">
              Financial & Sales Reports
            </h1>
            <p className="font-body-md text-on-surface-variant mt-1">
              Download certified revenue ledgers, inventory valuation manifests, and GST compliance CSV files.
            </p>
          </div>
          <AdminButton
            leftIcon={<Download className="w-4 h-4" />}
            onClick={() => handleDownload(reportsList[0])}
          >
            Download Latest Sales Report
          </AdminButton>
        </div>

        {/* Reports Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-space-lg">
          {reportsList.map((rep) => (
            <div
              key={rep.id}
              className="bg-white border border-outline-variant rounded-2xl p-6 shadow-sm hover:shadow-md transition-all flex flex-col justify-between space-y-4"
            >
              <div>
                <div className="flex justify-between items-start">
                  <div className="w-10 h-10 rounded-xl bg-primary text-white flex items-center justify-center">
                    <FileSpreadsheet className="w-5 h-5" />
                  </div>
                  <span className="text-xs font-bold text-primary bg-surface-container px-2.5 py-1 rounded-md border border-outline-variant">
                    {rep.category}
                  </span>
                </div>

                <h3 className="font-bold text-base text-primary mt-4">{rep.title}</h3>
                <p className="text-xs text-on-surface-variant mt-1">
                  Accounting Period: <span className="font-semibold text-primary">{rep.period}</span>
                </p>
                <p className="text-xs text-on-surface-variant mt-0.5">
                  Generated By: <span className="text-on-surface font-medium">{rep.generatedBy}</span>
                </p>
              </div>

              <div className="pt-4 border-t border-outline-variant flex items-center justify-between text-xs">
                <span className="font-mono text-on-surface-variant font-medium">{rep.format} • {rep.size}</span>
                <AdminButton
                  size="sm"
                  variant="outline"
                  onClick={() => handleDownload(rep)}
                >
                  <Download className="w-3.5 h-3.5 mr-1.5" />
                  {downloadingId === rep.id ? 'Downloading...' : 'Download CSV'}
                </AdminButton>
              </div>
            </div>
          ))}
        </div>
      </div>
    </AdminLayout>
  );
};

export default ReportsPage;
