/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c0c6db",
        "surface-container-highest": "#e5e2e3",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#151c27",
        "error": "#ba1a1a",
        "surface-tint": "#575e70",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#5e6572",
        "on-error": "#ffffff",
        "on-surface-variant": "#45464c",
        "on-secondary-fixed-variant": "#404754",
        "primary-fixed": "#dce2f7",
        "on-background": "#1b1b1d",
        "inverse-surface": "#303031",
        "tertiary-fixed": "#f9debf",
        "surface-dim": "#dcd9db",
        "on-tertiary-fixed-variant": "#55442d",
        "on-tertiary-container": "#968065",
        "on-tertiary-fixed": "#261906",
        "on-error-container": "#93000a",
        "tertiary-container": "#261906",
        "surface-container-high": "#eae7e9",
        "inverse-on-surface": "#f3f0f1",
        "on-surface": "#1b1b1d",
        "tertiary-fixed-dim": "#dcc2a4",
        "surface-bright": "#fcf8fa",
        "secondary-fixed-dim": "#c0c7d6",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#141b2b",
        "on-primary-fixed-variant": "#404758",
        "on-primary-container": "#7d8497",
        "surface": "#fcf8fa",
        "primary-fixed-dim": "#c0c6db",
        "tertiary": "#000000",
        "surface-container-low": "#f6f3f4",
        "background": "#fcf8fa",
        "outline-variant": "#c6c6cd",
        "outline": "#76777d",
        "secondary-fixed": "#dce2f3",
        "on-primary-fixed": "#141b2b",
        "surface-container": "#f0edee",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2e3",
        "secondary": "#585f6c",
        "on-secondary": "#ffffff",
        "secondary-container": "#dce2f3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "gutter": "1.5rem",
        "container-margin": "2rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
